export const todoTypes = {
  LOADING_TODOS: 'LOADING_TODOS',
  SUCCESS_TODOS: 'SUCCESS_TODOS',
  ERROR_TODOS: 'ERROR_TODOS'
}

export const postTypes = {
  LOADING_POSTS: 'LOADING_POSTS',
  SUCCESS_POSTS: 'SUCCESS_POSTS',
  ERROR_POSTS: 'ERROR_POSTS'
}
